apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-main
spec:
  selector:
    matchLabels:
      app: docker-main
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-main
    spec:
      containers:
      - name: docker-main
        image: mainj1.jar
        ports:
        - containerPort: 8080
